# Generated by Django 3.0.8 on 2020-07-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='jinhee', max_length=20),
            preserve_default=False,
        ),
    ]
